/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const API_BASE_URL: typeof import('./utils/fetcher').API_BASE_URL
  const CHOICE_COLORS: typeof import('./utils/collections').CHOICE_COLORS
  const COLLECTION_FIELD_TYPES: typeof import('./utils/collections').COLLECTION_FIELD_TYPES
  const DARK_CLASS: typeof import('./utils/theme').DARK_CLASS
  const EffectScope: typeof import('vue').EffectScope
  const FetcherError: typeof import('./utils/fetcher').FetcherError
  const MAX_SYSTEM_PROMPT_CHARS: typeof import('./stores/chatConfig').MAX_SYSTEM_PROMPT_CHARS
  const SIDEBAR_MAX_WIDTH: typeof import('./stores/layout').SIDEBAR_MAX_WIDTH
  const SIDEBAR_MIN_WIDTH: typeof import('./stores/layout').SIDEBAR_MIN_WIDTH
  const THEME_KEY: typeof import('./utils/theme').THEME_KEY
  const applyBrandColors: typeof import('./utils/brandColor').applyBrandColors
  const applyTheme: typeof import('./utils/theme').applyTheme
  const authenticatedImageUrl: typeof import('./utils/fetcher').authenticatedImageUrl
  const blocksAreEqual: typeof import('./utils/wikiBlocks').blocksAreEqual
  const blocksToEditorHtml: typeof import('./utils/wikiBlocks').blocksToEditorHtml
  const blocksToMarkdown: typeof import('./utils/wikiMarkdown').blocksToMarkdown
  const bootstrapTeamsSession: typeof import('./utils/teamsSession').bootstrapTeamsSession
  const buildScopeOptions: typeof import('./utils/wikiTreeOptions').buildScopeOptions
  const choiceClasses: typeof import('./utils/collections').choiceClasses
  const clearAuthMarkerCookie: typeof import('./utils/authCookie').clearAuthMarkerCookie
  const clearBrandColors: typeof import('./utils/brandColor').clearBrandColors
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const displayValue: typeof import('./utils/collections').displayValue
  const editorHtmlToBlocks: typeof import('./utils/wikiBlocks').editorHtmlToBlocks
  const effectScope: typeof import('vue').effectScope
  const emptyRecordData: typeof import('./utils/collections').emptyRecordData
  const exportWikiPageToPdf: typeof import('./utils/wikiPdf').exportWikiPageToPdf
  const fetcher: typeof import('./utils/fetcher').fetcher
  const filterKindFor: typeof import('./utils/collections').filterKindFor
  const findPageTitle: typeof import('./utils/wikiTreeOptions').findPageTitle
  const flagsFromScope: typeof import('./utils/wikiTreeOptions').flagsFromScope
  const floatTo16BitPCM: typeof import('./utils/pcm').floatTo16BitPCM
  const formatDateAsMMYYYY: typeof import('./utils/date').formatDateAsMMYYYY
  const formatDateTime: typeof import('./utils/date').formatDateTime
  const formatExactDateTime: typeof import('./utils/date').formatExactDateTime
  const formatRelativeIntl: typeof import('./utils/date').formatRelativeIntl
  const formatRelativeTime: typeof import('./utils/date').formatRelativeTime
  const generateScale: typeof import('./utils/brandColor').generateScale
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getStoredTheme: typeof import('./utils/theme').getStoredTheme
  const getTeamsAuthToken: typeof import('./utils/teamsSession').getTeamsAuthToken
  const h: typeof import('vue').h
  const hasAuthCookie: typeof import('./utils/authCookie').hasAuthCookie
  const inject: typeof import('vue').inject
  const isNarrowType: typeof import('./utils/collections').isNarrowType
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isTeamsHost: typeof import('./utils/teamsSession').isTeamsHost
  const isValidHexColor: typeof import('./utils/brandColor').isValidHexColor
  const looksLikeMarkdown: typeof import('./utils/markdownPaste').looksLikeMarkdown
  const markRaw: typeof import('vue').markRaw
  const matchesSearch: typeof import('./utils/collections').matchesSearch
  const nextTick: typeof import('vue').nextTick
  const normalizeHex: typeof import('./utils/brandColor').normalizeHex
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const pageOptionsForScope: typeof import('./utils/wikiTreeOptions').pageOptionsForScope
  const parseServerDate: typeof import('./utils/date').parseServerDate
  const parseUrlLine: typeof import('./utils/urlImportLines').parseUrlLine
  const parseUrlLines: typeof import('./utils/urlImportLines').parseUrlLines
  const prefersDark: typeof import('./utils/theme').prefersDark
  const provide: typeof import('vue').provide
  const ptViewMerge: typeof import('./volt/utils').ptViewMerge
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const recordLabel: typeof import('./utils/collections').recordLabel
  const ref: typeof import('vue').ref
  const refreshTeamsSession: typeof import('./utils/teamsSession').refreshTeamsSession
  const registerToastServiceGlobal: typeof import('./stores/toast').registerToastServiceGlobal
  const renderMarkdown: typeof import('./utils/markdown').renderMarkdown
  const renderMarkdownInline: typeof import('./utils/markdown').renderMarkdownInline
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveDark: typeof import('./utils/theme').resolveDark
  const scopeFromFlags: typeof import('./utils/wikiTreeOptions').scopeFromFlags
  const scopeLabel: typeof import('./utils/wikiTreeOptions').scopeLabel
  const sessionLabel: typeof import('./types/chatSession').sessionLabel
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const showToast: typeof import('./stores/toast').showToast
  const sortValue: typeof import('./utils/collections').sortValue
  const splitSubPath: typeof import('./utils/urlImportLines').splitSubPath
  const storeTheme: typeof import('./utils/theme').storeTheme
  const submitTeamsInvitationCode: typeof import('./utils/teamsSession').submitTeamsInvitationCode
  const teamsAuthHeaders: typeof import('./utils/teamsSession').teamsAuthHeaders
  const teamsState: typeof import('./utils/teamsSession').teamsState
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const urlLineToText: typeof import('./utils/urlImportLines').urlLineToText
  const urlLinesToText: typeof import('./utils/urlImportLines').urlLinesToText
  const useAgentInstructions: typeof import('./stores/agentInstructions').useAgentInstructions
  const useAiChat: typeof import('./stores/aiChat').useAiChat
  const useAiTests: typeof import('./stores/aiTests').useAiTests
  const useApiTokens: typeof import('./stores/apiTokens').useApiTokens
  const useApp: typeof import('./stores/main').useApp
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./stores/authStore').useAuthStore
  const useChatConfig: typeof import('./stores/chatConfig').useChatConfig
  const useChatSessions: typeof import('./stores/chatSessions').useChatSessions
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDocumentAssistant: typeof import('./stores/documentAssistant').useDocumentAssistant
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useKnowledgeConfig: typeof import('./stores/knowledgeConfig').useKnowledgeConfig
  const useLayout: typeof import('./stores/layout').useLayout
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useNotificationsStore: typeof import('./stores/notifications').useNotificationsStore
  const useOAuthClients: typeof import('./stores/oauthClients').useOAuthClients
  const usePasskeys: typeof import('./stores/passkeys').usePasskeys
  const usePostProcessingAgents: typeof import('./stores/postProcessingAgents').usePostProcessingAgents
  const useProtocol: typeof import('./stores/protocol').useProtocol
  const useReadOnly: typeof import('./stores/readonly').useReadOnly
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTheme: typeof import('./stores/theme').useTheme
  const useUrlImportJobs: typeof import('./stores/urlImportJobs').useUrlImportJobs
  const useWiki: typeof import('./stores/wiki').useWiki
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const watchTeamsTheme: typeof import('./utils/teamsSession').watchTeamsTheme
  const withTeamsWsToken: typeof import('./utils/teamsSession').withTeamsWsToken
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AiChatMode } from './stores/aiChat'
  import('./stores/aiChat')
  // @ts-ignore
  export type { ApiToken, CreateApiTokenInput } from './stores/apiTokens'
  import('./stores/apiTokens')
  // @ts-ignore
  export type { ChatAgentConfig } from './stores/chatConfig'
  import('./stores/chatConfig')
  // @ts-ignore
  export type { AssistantMessage, AssistResult } from './stores/documentAssistant'
  import('./stores/documentAssistant')
  // @ts-ignore
  export type { EmbeddingProviderStatus, EmbeddingSettings, EmbeddingBackfillResult, EmbeddingSettingsUpdate } from './stores/main'
  import('./stores/main')
  // @ts-ignore
  export type { Passkey } from './stores/passkeys'
  import('./stores/passkeys')
  // @ts-ignore
  export type { CreatedProtocol, ProcessResult } from './stores/protocol'
  import('./stores/protocol')
  // @ts-ignore
  export type { WikiImportOptions, IngestJob, WikiImageUpload } from './stores/wiki'
  import('./stores/wiki')
  // @ts-ignore
  export type { AiTestQuestionType, AiTestRunStatus, AiTestVerdict, AiTestClaimVerdict, AiTestSuite, AiTestQuestion, AiTestRunAggregates, AiTestRun, AiTestTrajectoryStep, AiTestTrajectory, AiTestClaim, AiTestJudgeReport, AiTestMetrics, AiTestScores, AiTestResult, AiTestSuiteDetail, AiTestRunDetail, AiTestSuiteInput, AiTestQuestionInput } from './types/aiTests'
  import('./types/aiTests')
  // @ts-ignore
  export type { ChatSession, ChatSessionMessage, ChatSessionDetail } from './types/chatSession'
  import('./types/chatSession')
  // @ts-ignore
  export type { JobStatus, Job, KnowledgeIngestResult, MessageType, NotificationMeta, UserMessage } from './types/notifications'
  import('./types/notifications')
  // @ts-ignore
  export type { OAuthClient, OAuthClientInput, OAuthClientCreated } from './types/oauthClients'
  import('./types/oauthClients')
  // @ts-ignore
  export type { PostProcessingAgent, PostProcessingAgentInput, PostProcessingAgentTestRun } from './types/postProcessingAgents'
  import('./types/postProcessingAgents')
  // @ts-ignore
  export type { UrlImportRunStatus, UrlImportUrlStatus, UrlImportJob, UrlImportJobUrl, UrlImportRunResultItem, UrlImportRun, UrlImportJobDetail, UrlImportJobInput } from './types/urlImport'
  import('./types/urlImport')
  // @ts-ignore
  export type { KnowledgeAccessLevel, Team, TeamMember, TenantMember, TenantInvitation, FoundUser } from './types/usermanagement'
  import('./types/usermanagement')
  // @ts-ignore
  export type { WikiTreeNode, WikiDragState, WikiMovePayload, WikiTeamSection, WikiTree, WikiPage, KnowledgeAttributeDefinition, WikiKnowledgeConfig, AgentInstructions, WikiParserFeatures, WikiParserModality, WikiParserCapabilities, WikiTocEntry, WikiBlock, WikiScope, WikiSearchResult, WikiSearchMode, WikiOutgoingLink, WikiBacklink, WikiRelatedPage } from './types/wiki'
  import('./types/wiki')
  // @ts-ignore
  export type { BrandColors } from './utils/brandColor'
  import('./utils/brandColor')
  // @ts-ignore
  export type { CollectionFieldType, CollectionFieldChoice, CollectionFieldOptions, CollectionField, CollectionSettings, Collection, CollectionRecord, FilterKind } from './utils/collections'
  import('./utils/collections')
  // @ts-ignore
  export type { FetcherError } from './utils/fetcher'
  import('./utils/fetcher')
  // @ts-ignore
  export type { TeamsStatus, TeamsFailure, TeamsTheme } from './utils/teamsSession'
  import('./utils/teamsSession')
  // @ts-ignore
  export type { ThemePreference } from './utils/theme'
  import('./utils/theme')
  // @ts-ignore
  export type { ParsedUrlLine } from './utils/urlImportLines'
  import('./utils/urlImportLines')
  // @ts-ignore
  export type { WikiPdfBranding, WikiPdfExportOptions } from './utils/wikiPdf'
  import('./utils/wikiPdf')
  // @ts-ignore
  export type { PageOption } from './utils/wikiTreeOptions'
  import('./utils/wikiTreeOptions')
}
