/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const API_BASE_URL: typeof import('./utils/fetcher').API_BASE_URL
  const DARK_CLASS: typeof import('./utils/theme').DARK_CLASS
  const EffectScope: typeof import('vue').EffectScope
  const FetcherError: typeof import('./utils/fetcher').FetcherError
  const THEME_KEY: typeof import('./utils/theme').THEME_KEY
  const applyTheme: typeof import('./utils/theme').applyTheme
  const blocksAreEqual: typeof import('./utils/wikiBlocks').blocksAreEqual
  const blocksToEditorHtml: typeof import('./utils/wikiBlocks').blocksToEditorHtml
  const clearAuthMarkerCookie: typeof import('./utils/authCookie').clearAuthMarkerCookie
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const editorHtmlToBlocks: typeof import('./utils/wikiBlocks').editorHtmlToBlocks
  const effectScope: typeof import('vue').effectScope
  const exportWikiPageToPdf: typeof import('./utils/wikiPdf').exportWikiPageToPdf
  const fetcher: typeof import('./utils/fetcher').fetcher
  const floatTo16BitPCM: typeof import('./utils/pcm').floatTo16BitPCM
  const formatDateAsMMYYYY: typeof import('./utils/date').formatDateAsMMYYYY
  const formatRelativeTime: typeof import('./utils/date').formatRelativeTime
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getStoredTheme: typeof import('./utils/theme').getStoredTheme
  const h: typeof import('vue').h
  const hasAuthCookie: typeof import('./utils/authCookie').hasAuthCookie
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const prefersDark: typeof import('./utils/theme').prefersDark
  const provide: typeof import('vue').provide
  const ptViewMerge: typeof import('./volt/utils').ptViewMerge
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const registerToastServiceGlobal: typeof import('./stores/toast').registerToastServiceGlobal
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveDark: typeof import('./utils/theme').resolveDark
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const showToast: typeof import('./stores/toast').showToast
  const storeTheme: typeof import('./utils/theme').storeTheme
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useApp: typeof import('./stores/main').useApp
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./stores/authStore').useAuthStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDocumentAssistant: typeof import('./stores/documentAssistant').useDocumentAssistant
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useLayout: typeof import('./stores/layout').useLayout
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useNotificationsStore: typeof import('./stores/notifications').useNotificationsStore
  const useProtocol: typeof import('./stores/protocol').useProtocol
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTheme: typeof import('./stores/theme').useTheme
  const useUrlImportJobs: typeof import('./stores/urlImportJobs').useUrlImportJobs
  const useWiki: typeof import('./stores/wiki').useWiki
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AssistantMessage, AssistResult } from './stores/documentAssistant'
  import('./stores/documentAssistant')
  // @ts-ignore
  export type { CreatedProtocol, ProcessResult } from './stores/protocol'
  import('./stores/protocol')
  // @ts-ignore
  export type { WikiImportOptions, WikiImageUpload } from './stores/wiki'
  import('./stores/wiki')
  // @ts-ignore
  export type { UrlImportRunStatus, UrlImportUrlStatus, UrlImportJob, UrlImportJobUrl, UrlImportRunResultItem, UrlImportRun, UrlImportJobDetail, UrlImportJobInput } from './types/urlImport'
  import('./types/urlImport')
  // @ts-ignore
  export type { Team, TeamMember, TenantMember, TenantInvitation, FoundUser } from './types/usermanagement'
  import('./types/usermanagement')
  // @ts-ignore
  export type { WikiTreeNode, WikiTeamSection, WikiTree, WikiPage, WikiBlock, WikiScope, WikiSearchResult } from './types/wiki'
  import('./types/wiki')
  // @ts-ignore
  export type { FetcherError } from './utils/fetcher'
  import('./utils/fetcher')
  // @ts-ignore
  export type { ThemePreference } from './utils/theme'
  import('./utils/theme')
  // @ts-ignore
  export type { WikiPdfBranding, WikiPdfExportOptions } from './utils/wikiPdf'
  import('./utils/wikiPdf')
}
