/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTopBar: typeof import('./components/layout/AppTopBar.vue')['default']
    Avatar: typeof import('./volt/Avatar.vue')['default']
    Badge: typeof import('./volt/Badge.vue')['default']
    BlockEditor: typeof import('./components/editor/BlockEditor.vue')['default']
    Breadcrumb: typeof import('./volt/Breadcrumb.vue')['default']
    Button: typeof import('./volt/Button.vue')['default']
    Card: typeof import('./volt/Card.vue')['default']
    Checkbox: typeof import('./volt/Checkbox.vue')['default']
    Chip: typeof import('./volt/Chip.vue')['default']
    ConfirmDialog: typeof import('./volt/ConfirmDialog.vue')['default']
    CronField: typeof import('./components/jobs/CronField.vue')['default']
    DataTable: typeof import('./volt/DataTable.vue')['default']
    DatePicker: typeof import('./volt/DatePicker.vue')['default']
    Default: typeof import('./components/layout/Default.vue')['default']
    Dialog: typeof import('./volt/Dialog.vue')['default']
    DocumentAssistantPanel: typeof import('./components/wiki/DocumentAssistantPanel.vue')['default']
    EditorBubbleMenu: typeof import('./components/editor/EditorBubbleMenu.vue')['default']
    FileUpload: typeof import('./volt/FileUpload.vue')['default']
    ImageCropperDialog: typeof import('./components/common/ImageCropperDialog.vue')['default']
    InputText: typeof import('./volt/InputText.vue')['default']
    InvitationsList: typeof import('./components/manage/InvitationsList.vue')['default']
    ManageHeader: typeof import('./components/manage/ManageHeader.vue')['default']
    ManageTabs: typeof import('./components/manage/ManageTabs.vue')['default']
    MarkdownPasteDialog: typeof import('./components/wiki/MarkdownPasteDialog.vue')['default']
    MarkdownRenderer: typeof import('./components/MarkdownRenderer.vue')['default']
    Menu: typeof import('./volt/Menu.vue')['default']
    Message: typeof import('./volt/Message.vue')['default']
    MultiSelect: typeof import('./volt/MultiSelect.vue')['default']
    OverlayBadge: typeof import('./volt/OverlayBadge.vue')['default']
    Popover: typeof import('./volt/Popover.vue')['default']
    ProtocolDialog: typeof import('./components/protocol/ProtocolDialog.vue')['default']
    ProtocolRecorder: typeof import('./components/protocol/ProtocolRecorder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./volt/SecondaryButton.vue')['default']
    Select: typeof import('./volt/Select.vue')['default']
    SelectButton: typeof import('./volt/SelectButton.vue')['default']
    SlashMenu: typeof import('./components/editor/SlashMenu.vue')['default']
    Textarea: typeof import('./volt/Textarea.vue')['default']
    Toast: typeof import('./volt/Toast.vue')['default']
    ToggleButton: typeof import('./volt/ToggleButton.vue')['default']
    ToolCallCard: typeof import('./components/wiki/ToolCallCard.vue')['default']
    WikiAiChat: typeof import('./components/wiki/WikiAiChat.vue')['default']
    WikiImportDialog: typeof import('./components/wiki/WikiImportDialog.vue')['default']
    WikiLinkMenu: typeof import('./components/editor/WikiLinkMenu.vue')['default']
    WikiReferences: typeof import('./components/wiki/WikiReferences.vue')['default']
    WikiSidebar: typeof import('./components/wiki/WikiSidebar.vue')['default']
    WikiSidebarSection: typeof import('./components/wiki/WikiSidebarSection.vue')['default']
    WikiTableOfContents: typeof import('./components/wiki/WikiTableOfContents.vue')['default']
    WikiTreeItem: typeof import('./components/wiki/WikiTreeItem.vue')['default']
  }
}
